update yml file

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -1,26 +1,45 @@
-name: Run App Every 30 Minutes
+# YAML file for a GitHub Actions workflow to Keep The Server Running
 
-on:
-  schedule:
+# Define the name of the workflow
+name: Keep API Server Running
+
+# Specify when the workflow should run, in this case, every 30 minutes
+on:  
+  schedule:    
     - cron: '*/30 * * * *'
 
+# Define the jobs that will be executed
 jobs:
-  run_app:
+  # Job to call a website
+  call_api:  
+    # Specify the operating system for the job
     runs-on: ubuntu-latest
 
+    # Specify the steps to be executed within the job
     steps:
+    # Step to checkout the code from the repository
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
+    - name: Wait for server to start
+      run: sleep 30s  
 
-    - name: Install dependencies
+    - name: Call API
+      id: api_call
       run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-
-    - name: Run the application
-      run: python run.py
+        # Perform API call and capture the HTTP status code
+        response=$(curl -sS -w "%{http_code}" https://football-players-charts.onrender.com/api/get_player_data)
+        
+        # Extract the HTTP status code from the response
+        http_status_code=$(echo "$response" | tail -n1)
+        
+        # Print the API response for debugging purposes
+        echo "API Response: $response"
+        
+        # Check if the API call was successful (HTTP status code 200)
+        if [ "$http_status_code" = "200" ]; then
+          echo "API call successful, exiting with success"
+        else
+          echo "API call unsuccessful, exiting with failure"
+          exit 1
+        fi
